{
 "title": "Lana App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Baskets Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(basket_created)" }
   ]
  },
  {
   "title": "Items Added to Baskets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(basket_items_added)" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_milliseconds_count"
    }
   ]
  }
 ]
}